version: '3'

services:
    web:
        build: .
        ports:
            - '5000:5000'
        # network-mode: host
        environment:
            FLASK_ENV: 'development'
            FLASK_DEBUG: 'True'
            SECRET_KEY: ''
            DATABASE_URL: ''
            SQLALCHEMY_TRACK_MODIFICATIONS: 'False'
    db:
        image: postgres
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
            POSTGRES_DB: blog
        ports:
            - '5432:5432'
    
